--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: quotes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.quotes (
    id bigint NOT NULL,
    "character" character varying(255),
    poster character varying(255),
    quote character varying(255),
    title character varying(255)
);


ALTER TABLE public.quotes OWNER TO postgres;

--
-- Name: quotes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.quotes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.quotes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: quotes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.quotes (id, "character", poster, quote, title) FROM stdin;
1	Vander	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	When people look up to you, you don’t get to be selfish.	Arcane season 1, episode 1
3	Heimerdinger	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Imprisonment. What a curious principle. We confine the physical body, yet the mind is still free.	Arcane season 1, episode 2
4	Jayce Talis	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Surely, we, the pioneers of science, can use it for good. We’re the champions of discovery. Why fear it when we can master it?	Arcane season 1, episode 2
5	Heimerdinger	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	If dangerous ideas didn’t excite the imagination, we would never wander astray.	Arcane season 1, episode 2
6	Silco	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	here’s a monster inside all of us.	Arcane season 1, episode 2
7	Viktor	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Nobody’s ever believed in me. A poor cripple from the undercity. I was an outsider the moment I stepped foot in Piltover. I didn’t have the benefits of a patron or a name. I simply believed in myself.	Arcane season 1, episode 2
8	Viktor	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	When you’re going to change the world, don’t ask for permission.	Arcane season 1, episode 2
9	Vi	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	You know, Powder, what makes you different makes you strong. Always remember that, okay?	Arcane season 1, episode 2
10	Vander	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	You’ve got a good heart. Don’t ever lose it. No matter how the world tries to break you. Protect the family.	Arcane season 1, episode 2
11	Mel Medarda	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	I recognize that any worthwhile venture involves risk.	Arcane season 1, episode 3
12	Silco	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Betrayal, that pain that feels like it’ll eat you from the inside out, can either break you or forge you into something greater.	Arcane season 1, episode 5
13	Singed	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Loneliness is often the byproduct of a gifted mind.	Arcane season 1, episode 6
14	Heimerdinger	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	It’s a sad truth that those who shine brightest often burn fastest.	Arcane season 1, episode 6
15	Mel Medarda	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	We can’t change what fate has in store for us, but we don’t have to face it alone.	rcane season 1, episode 6
16	Singed	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Love and legacy are the sacrifices we make for progress.	Arcane season 1, episode 7
17	Viktor	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	There is always a choice.	Arcane season 1, episode 7
18	Ambessa Medarda	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	He fancies himself a fox among the wolves. But mark me, child, if you want to last in this world, you must learn to be both the fox and the wolf.	Arcane season 1, episode 8
19	Ambessa Medarda	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	A wolf has no mercy.	Arcane season 1, episode 8
20	Singed	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Sometimes death is a mercy.	Arcane season 1, episode 8
21	Ambessa Medarda	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	I would set the world ablaze to protect our family.	Arcane season 1, episode 9
22	Ekko	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	It’s not enough to give people what they need to surive, you have to give them what they need to live.	Arcane season 1, episode 9
23	Silco	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Is there anything so undoing as a daughter?	Arcane season 1, episode 9
24	Silco	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	I never would have given you to them. Not for anything. Don’t cry. You’re perfect.	Arcane season 1, episode 9
25	Jayce Talis	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	You think it’s so easy? To turn your back while your city looks to you for salvation? To cling to principles while your best friend bleeds out in your arms? I never asked for this.	Arcane season 2, episode 2
26	Caitlyn Kiramman	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Why is peace always the justification for violence?	Arcane season 2, episode 4
27	Singed	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	No beast is more savage than a man.	Arcane season 2, episode 5
28	Singed	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Why does anyone commit acts other deem unspeakable? For love.	Arcane season 2, episode 5
29	Viktor	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Knowledge is a paradox. The more one understands, the more one realizes the vastness of his ignorance.	Arcane season 2, episode 6
2	Vi	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Wee’ve all had bad days. But we learn. And we stick together.	Arcane season 1, episode 1
30	Viktor	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Evolution has a destination. Not to combat nature, but to supersede it. The final, glorious evolution.	Arcane season 2, episode 6
31	Silco	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	Greatest thing we can do in life is find the power to forgive.	Arcane season 2, episode 7
32	Ambessa Medarda	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	We do not lament a warrior’s death. We avenge it.	Arcane season 2, episode 8
33	Silco	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	I think the cycle only ends when we find the will to walk away.	Arcane season 2, episode 8
34	Jinx	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	m always with you. Even when we’re worlds apart.	Arcane season 2, episode 9
35	Jayce Talis	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	You’ve always wanted to cure what you thought were weaknesses. Your leg. Your disease. But you were never broken, Viktor. There is beauty in imperfections.	Arcane season 2, episode 9
36	Viktor	https://m.media-amazon.com/images/M/MV5BOWJhYjdjNWEtMWFmNC00ZjNkLThlZGEtN2NkM2U3NTVmMjZkXkEyXkFqcGc@._V1_SX300.jpg	There is no prize to perfection. Only an end to pursuit.	Arcane season 2, episode 9
\.


--
-- Name: quotes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.quotes_id_seq', 1, false);


--
-- Name: quotes quotes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.quotes
    ADD CONSTRAINT quotes_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

